### ISSUE TITLE
Automation Step Execution fails when it is creating the image

### ISSUE THREAD

**Issue by zzmohammed** [aws-samples/aws-systemsmanagerautomation-with-asglifecyclehooks#2]
get this message when I try to test this out with terminating EC2....

Automation Step Execution fails when it is creating the image. Get Exception from CreateImage API of ec2 Service. Exception Message from CreateImage API: [Invalid value 'i-02270eb84383eb2c3' for instanceId. Instance is not in state 'running' or 'stopping' or 'stopped' (Service: AmazonEC2; Status Code: 400; Error Code: InvalidParameterValue; Request ID: feb689ef-b2c0-4464-98be-2cc49d7c8625; Proxy: null)]. Please refer to Automation Service Troubleshooting Guide for more diagnosis details.

**Comment by aaalzand** [comment]
Thanks for reaching out. Are you still running into this issue? I will review CloudTrail to check the event timeline if there is another process or API that terminates the instance before executing the automation document.
